### PR TITLE
fix bs (untested)

### PR DESCRIPTION
**Pull request by PinkiePieStyle**
why using thread and do work in init

### CODE REVIEW

**Comment by iGio90** [comment]
Because if you put code the in run() it will give us that yield error

**Comment by iGio90** [comment]
Thats the reason i put it outside run()

**Comment by PinkiePieStyle** [comment]
steps to reproduce?

**Comment by iGio90** [comment]
Every time i disasm with cs.disasm() in non-main-thread it throws that yield error we were discussing times ago. Maybe try in ur ubuntu VM if it act the same

**Comment by PinkiePieStyle** [comment]
try with last one

Its again all the complicated bs you created

looking in files it seems:

- Disassembler() instance is created in Dwarf()
- this instance uses self.dwarf wich holds Dwarf() with self.disassembler in and connects to signal in Dwarf()
- Disassembler() creates the Thread wich also holds Dwarf() with disasm in and the thread now
- in disasmview "disasm()" calls "dwarf.disasminst.disasm()" wich then connects callback from ui

and so on - simple capstone.disasm() call is placed over 3 files now

there was no reason to change it this way

no idea why it needs Disassembler() wich holds only the arch/mode from arch_changed
so why ui.disasm cant create the thread?
it was a signal/slot before and everyone was able to connect

**Comment by iGio90** [comment]
Are you a fkin fuck? XD you pushed my balls 3 months to kill all cs things from disasm UI!!!!!!! Now that i love everything out you ask me why i did this? Im in holydays right now between! Gonna test it asap, if you have no issues just emerge it and eventually we will figure out later that yield thingy

**Pull request closed without merging**
